apiVersion: apps/v1
kind: Deployment
metadata:
  name: radev-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radev
  template:
    metadata:
      labels:
        app: radev
    spec:
      containers:
      - name: radev
        image: 279395902119.dkr.ecr.us-east-1.amazonaws.com/radev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: radev
    k8s-app: radev
  name: radev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: radev
